export const FETCH_BODY_REQUEST = 'FETCH_BODY_REQUEST';
export const FETCH_BODY_SUCCESS = 'FETCH_BODY_SUCCESS';
export const FETCH_BODY_FAILURE = 'FETCH_BODY_FAILURE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const FETCH_DATA2_REQUEST = 'FETCH_DATA2_REQUEST';
export const FETCH_DATA2_SUCCESS = 'FETCH_DATA2_SUCCESS';
export const FETCH_DATA2_FAILURE = 'FETCH_DATA2_FAILURE';